import { assertMeetingRetained, assertEmptyMeetingDeletable } from './meeting-deletion-check'
import { test, expect } from '@playwright/test'

test('real Retro modified approval creates one action with durable audit', async ({ page, request }) => {
  await page.goto('/#/ai')
  await page.locator('#login-user').fill('李锐铭')
  await page.locator('#login-pass').fill('123456')
  await page.locator('#login-form').getByRole('button', { name: '登录', exact: true }).click()
  await expect(page.locator('#login')).not.toBeVisible()
  await page.locator('#meeting-save-form input[name=title]').fill('Retro真实联调')
  await page.locator('#meeting-save-form textarea').fill('决定完善发布检查表，负责人和截止时间待确认。')
  await page.locator('#meeting-save-form button').click()
  await expect(page.locator('#saved-transcript')).toHaveText('决定完善发布检查表，负责人和截止时间待确认。')
  const meetingId = await page.locator('#meeting-select').inputValue()
  const token = await page.evaluate(() => localStorage.getItem('aiguanli_token'))
  const headers = { Authorization: `Bearer ${token}` }, base = 'http://127.0.0.1:18180'
  const read = async path => {
    const response = await request.get(base + path, { headers })
    expect(response.status()).toBe(200)
    return response.json()
  }
  const stories = await read('/api/stories'), tasks = await read('/api/tasks'), profiles = await read('/api/members/profiles')
  const owner = profiles.find(member => member.role === 'owner')
  expect(owner).toBeTruthy()
  const actionsPath = `/api/meetings/${meetingId}/action-items`
  await page.getByRole('button', { name: '打开会议 Sprint Retro' }).click()
  const panel = page.getByRole('region', { name: 'Retro行动提案', exact: true })
  await panel.getByRole('button', { name: '分析Sprint Retro', exact: true }).click()
  await expect(panel).toContainText('原始事项：完善发布检查表', { timeout: 20000 })
  await expect(panel).toContainText('负责人：未确定 · 截止时间：未确定')
  const analysisId = await panel.getByLabel('Retro分析记录').inputValue()
  const recordPath = `/api/meetings/${meetingId}/retro-analyses/${analysisId}`
  const original = await read(recordPath)
  await assertMeetingRetained(request, base, headers, meetingId, recordPath)
  await assertEmptyMeetingDeletable(request, base, headers)
  expect(original.result.proposed_actions[0].changes).toMatchObject({ owner_id: null, deadline_text: null })
  expect(await read(actionsPath)).toEqual([])
  const execute = () => request.post(base + recordPath + '/proposal-executions', { headers, data: { proposal_id: 'p1' } })
  expect((await execute()).status()).toBe(409)
  await panel.getByLabel('审核决定').selectOption('modify_and_approve')
  await panel.getByLabel('批准后的事项', { exact: true }).fill('完善发布和回滚检查表')
  await panel.getByLabel('批准后的负责人').selectOption(String(owner.user_id))
  await panel.getByLabel('批准后的截止时间（留空表示未确定）').fill('下周五前')
  await panel.getByLabel('修改原因（必填）').fill('人工确认负责人及截止时间')
  await panel.getByRole('button', { name: '提交审核决定' }).click()
  await expect(panel).toContainText('批准后的事项：完善发布和回滚检查表')
  expect(await read(actionsPath)).toEqual([])
  await panel.getByRole('button', { name: '执行已批准变更' }).click()
  await expect(panel).toContainText('执行结果已确认')
  const executions = await read(recordPath + '/proposal-executions')
  expect(executions).toHaveLength(1)
  await assertMeetingRetained(request, base, headers, meetingId, recordPath)
  const actions = await read(actionsPath)
  expect(actions).toHaveLength(1)
  expect(actions[0]).toMatchObject({ id: executions[0].action_item_id, title: '完善发布和回滚检查表', owner_id: owner.user_id, deadline_text: '下周五前', status: 'open', analysis_id: analysisId })
  const logsPath = actionsPath + '/' + actions[0].id + '/logs'
  const logs = await read(logsPath)
  expect(logs).toHaveLength(1)
  expect(logs[0].id).toBe(executions[0].action_item_log_id)
  expect(JSON.parse(logs[0].approved_proposal_json).changes).toMatchObject({ title: actions[0].title, owner_id: owner.user_id, deadline_text: '下周五前' })
  const repeats = await Promise.all([execute(), execute()])
  for (const response of repeats) { expect(response.status()).toBe(200); expect(await response.json()).toEqual(executions[0]) }
  expect(await read(actionsPath)).toEqual(actions)
  expect(await read(logsPath)).toEqual(logs)
  const analyzePath = `http://127.0.0.1:18190/api/meetings/${meetingId}/retro/analyze`
  const retry = await request.post(analyzePath, { headers, data: { client_request_id: original.client_request_id, meeting_type: 'sprint_retrospective' } })
  expect(retry.status()).toBe(200)
  expect((await retry.json()).analysis_id).toBe(analysisId)
  expect(await read(recordPath)).toEqual(original)
  expect(await read('/api/stories')).toEqual(stories)
  expect(await read('/api/tasks')).toEqual(tasks)
  expect(await read('/api/members/profiles')).toEqual(profiles)
  expect((await request.post(base + recordPath + '/proposal-executions', { data: { proposal_id: 'p1' } })).status()).toBe(401)
  const login = await request.post(base + '/api/auth/login', { data: { username: '成员5', password: '123456' } })
  expect(login.status()).toBe(200)
  const viewer = { Authorization: `Bearer ${(await login.json()).access_token}` }
  expect((await request.post(base + recordPath + '/proposal-executions', { headers: viewer, data: { proposal_id: 'p1' } })).status()).toBe(403)
  expect((await request.post(base + recordPath + '/proposal-reviews', { headers: viewer, data: { proposal_id: 'p1', decision: 'approve', reason: '' } })).status()).toBe(403)
  expect((await request.post(analyzePath, { headers: viewer, data: { client_request_id: 'viewer-denied', meeting_type: 'sprint_retrospective' } })).status()).toBe(403)
  expect((await request.get(base + actionsPath, { headers: viewer })).status()).toBe(200)
  await page.reload()
  await page.getByRole('button', { name: '打开会议 Sprint Retro' }).click()
  await expect(panel).toContainText(`审计 #${executions[0].action_item_log_id}`)
  const business = panel.getByRole('region', { name: '已创建行动项' })
  await expect(business).toContainText('完善发布和回滚检查表')
  await business.getByRole('button', { name: '查看行动项审计' }).click()
  await expect(business).toContainText(`审计 #${logs[0].id}`)
  await expect(panel.getByRole('button', { name: '执行已批准变更' })).toHaveCount(0)
})
